public class ArthimaticCalc2 {
    public Integer Addition(Integer x, Integer y) {
        integer z = x + y;
        return z;
        
    }

    public Integer Subtraction(integer x, Integer y){
        Integer z = x-y;
        return z;
        
    
    }

    public Integer Multiplication(integer x, Integer y, Integer m){
        
        Integer z = x*y*m;

        return z;
        
    
    }
}
