public class ArthimaticCalculations {
    public void Addition(Integer x, Integer y) {
        integer z = x + y;
        system.debug('Sum => ' + z);

    }

    public void Subtraction(integer x, Integer y){
        Integer z = x-y;
        System.debug('Subtraction => ' + z);
    
    }

    public void Multiplication(integer x, Integer y, Integer m){
        Integer z = x*y*m;
        System.debug('Multiplication => ' + z);
    
    }
}
