public class SalesforceDeveloper {
    public void myFirstCode() {
        String city = 'İstanbul';
        System.debug(city);
        String movie = 'Benim Dünyam';
        System.debug(movie);
        String season = 'autumn';
        System.debug(season);

    }
    public void myFavorites (){
        Integer myFavariteNumber = 7;
        System.debug(myFavariteNumber);
        String myFavoritecity = 'İstanbul';
        System.debug(myFavoritecity);
        System.debug('Favori Numaram => ' + myFavariteNumber + ' Favori Şehrim => ' + myFavoritecity );
    }
}
